<a href="https://colab.research.google.com/github/florencialastarria/UI1/blob/main/Load_tasas_de_mortalidad_especifica_cancer_ajustada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Setup

In [ ]:
#Conectar a Drive
import pandas as pd
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

path_dw='/content/drive/MyDrive/DSP 2025-1/cursos/PHDMISP2 Métodos de investigación en salud pública/seminario/Trabajo seminario/3 Data warehouse/'
path_tasas='/content/drive/MyDrive/DSP 2025-1/cursos/PHDMISP2 Métodos de investigación en salud pública/seminario/Trabajo seminario/4 Tasas y razones de mortalidad/'

Mounted at /content/drive

#Cargar fuentes

In [ ]:
df_defunciones = pd.read_parquet(path_dw + 'DW_defunciones.parquet')
df_poblacion = pd.read_parquet(path_dw + 'DW_INE.parquet')
df_crude_rates_year = pd.read_parquet(path_tasas + 'TMC_A.parquet')
df_crude_rates_comuna_year = pd.read_parquet(path_tasas + 'TMC_AC.parquet')
df_age_adjusted_rates = pd.read_parquet(path_tasas + 'TMA_AC.parquet')

display(df_defunciones.head())
display(df_poblacion.head())
display(df_crude_rates_year.head())
display(df_crude_rates_comuna_year.head())
display(df_age_adjusted_rates.head())

# --- Verification of Population Data Consistency ---
# Calculate total population for Comuna 1101, Año 2002 from df_poblacion
population_df_poblacion_1101_2002 = df_poblacion[(df_poblacion['Comuna'] == 1101) & (df_poblacion['Año'] == 2002)]['Poblacion'].sum()

# Get total population for Comuna 1101, Año 2002 from df_crude_rates_comuna_year
population_df_crude_rates_1101_2002 = df_crude_rates_comuna_year[(df_crude_rates_comuna_year['Comuna'] == 1101) & (df_crude_rates_comuna_year['Año'] == 2002)]['Total_Population'].iloc[0]

print(f"\nTotal population for Comuna 1101, Año 2002 from df_poblacion (sum of age/sex groups): {population_df_poblacion_1101_2002}")
print(f"Total population for Comuna 1101, Año 2002 from df_crude_rates_comuna_year: {population_df_crude_rates_1101_2002}")

# You can add more checks for other communes/years as needed
# --- End Verification ---

,AÑO,FECHA_DEF,Sexo,Edad,Comuna,COMUNA,NOMBRE_REGION,DIAG1,CAPITULO_DIAG1,GLOSA_CAPITULO_DIAG1,...,DIAG2,CAPITULO_DIAG2,GLOSA_CAPITULO_DIAG2,CODIGO_GRUPO_DIAG2,GLOSA_GRUPO_DIAG2,CODIGO_CATEGORIA_DIAG2,GLOSA_CATEGORIA_DIAG2,CODIGO_SUBCATEGORIA_DIAG2,GLOSA_SUBCATEGORIA_DIAG2,LUGAR_DEFUNCION
262,2015,2015-01-11,2.0,0.333333,13127,Recoleta,Metropolitana de Santiago,T71X,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,W840,V01-Y98,Causas externas de morbilidad y de mortalidad,W75-W84,Otros accidentes que obstruyen la respración,W84,Obstrucción no especificada de la respiración,W840,OBSTRUCCIÓN NO ESPECIFICADA DE LA RESPIRACIÓN ...,Otro
374,2011,2011-09-15,1.0,29.000000,1401,Pozo Almonte,De Tarapacá,S279,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,V853,V01-Y98,Causas externas de morbilidad y de mortalidad,V80-V89,Otros accidentes de transporte terrestre,V85,Ocupante de vehículo especial (de motor) para ...,V853,OCUPANTE NO ESPECIFICADO(A) DE VEHÍCULO ESPECI...,Otro
558,2009,2009-01-18,1.0,17.000000,13127,Recoleta,Metropolitana de Santiago,S219,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,X990,V01-Y98,Causas externas de morbilidad y de mortalidad,X85-Y09,Agresiones,X99,Agresión con objeto cortante,X990,AGRESIÓN CON OBJETO CORTANTE OCURRIDA EN UNA V...,Otro
579,2016,2016-01-31,1.0,20.000000,8203,Cañete,Del Bíobío,T751,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,W699,V01-Y98,Causas externas de morbilidad y de mortalidad,W65-W74,Ahogamiento y sumersión accidentales,W69,Ahogamiento y sumersión mientras se está en ag...,W699,AHOGAMIENTO Y SUMERSIÓN MIENTRAS SE ESTA EN AG...,Otro
596,2006,2006-01-17,1.0,50.000000,13108,Independencia,Metropolitana de Santiago,T751,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,W748,V01-Y98,Causas externas de morbilidad y de mortalidad,W65-W74,Ahogamiento y sumersión accidentales,W74,Ahogamiento y sumersión no especificados,W748,AHOGAMIENTO Y SUMERSIÓN NO ESPECIFICADOS OCURR...,Otro

   Comuna  Sexo (1=Hombre 2=Mujer)       Grupo edad   Año  Poblacion
0    1101                        1            0 Año  2002       1469
1    1101                        1    80 años y más  2002        604
2    1101                        1    De 1 a 4 años  2002       5859
3    1101                        1  De 10 a 14 años  2002       7570
4    1101                        1  De 15 a 19 años  2002       7617

    Año  Total_Deaths  Total_Population  Crude_Rate
0  2002         81079          15691701  516.699878
1  2003         83672          15856977  527.666780
2  2004         86138          16022133  537.618805
3  2005         86102          16183489  532.036077
4  2006         85639          16347890  523.853537

    Año  Comuna  Total_Deaths  Total_Population  Crude_Rate
0  2002    1101           972          173611.0  559.872358
1  2002    1401            25            9833.0  254.245907
2  2002    1402             1            1325.0   75.471698
3  2002    1403             1            1636.0   61.124694
4  2002    1404             5            2615.0  191.204589

,Año,Comuna,Total_Expected_Deaths,Total_Standard_Population,Age_Adjusted_Rate
0,2002,1101,2.526201e+06,309776434,815.491739
1,2002,1107,0.000000e+00,309776434,0.000000
2,2002,1401,1.222062e+06,309776434,394.498154
3,2002,1402,3.452746e+05,309776434,111.459277
4,2002,1403,1.953036e+05,309776434,63.046644

Total population for Comuna 1101, Año 2002 from df_poblacion (sum of age/sex groups): 0
Total population for Comuna 1101, Año 2002 from df_crude_rates_comuna_year: 173611.0

#Preparación de datos

In [ ]:
# Standardize column names (optional, but good practice)
df_defunciones.columns = df_defunciones.columns.str.strip().str.replace(' ', '_')
df_poblacion.columns = df_poblacion.columns.str.strip().str.replace(' ', '_').str.replace('(1=Hombre_2=Mujer)', '', regex=False)

# Rename the 'Sexo_' column to 'Sexo' in df_poblacion
df_poblacion.rename(columns={'Sexo_': 'Sexo'}, inplace=True)

# Rename 'AÑO' in df_defunciones to 'Año' to match df_poblacion
df_defunciones.rename(columns={'AÑO': 'Año'}, inplace=True)

# Convert 'Edad' in df_defunciones to integer
df_defunciones['Edad'] = df_defunciones['Edad'].astype(int)

# Convert 'Sexo' in df_defunciones to integer
df_defunciones['Sexo'] = df_defunciones['Sexo'].astype(int)

# --- Age Grouping for Cancer Analysis ---
# Define new age group bins and labels for the desired grouping (0-19, 20-59, 60+)
new_age_bins = [-1, 19, 59, float('inf')]
new_age_labels = ['0-19', '20-59', '60+']

# The 'Edad' column in df_poblacion is already in integer format from the parquet file,
# so direct mapping from 'Grupo_edad' string is not necessary for creating the new age groups with pd.cut.
# If you need to work with the original 'Grupo_edad' strings for other purposes, keep the mapping code.
# Otherwise, this cell will now focus on preparing data for the new age grouping in subsequent cells.


# Convert 'Año' in df_poblacion to integer
df_poblacion['Año'] = df_poblacion['Año'].astype(int)


# Display data types and head to confirm changes
display(df_defunciones.info())
display(df_poblacion.info())

display(df_defunciones.head())
display(df_poblacion.head())

<class 'pandas.core.frame.DataFrame'>
Index: 1721164 entries, 262 to 2660307
Data columns (total 26 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Año                        int64
 1   FECHA_DEF                  object
 2   Sexo                       int64
 3   Edad                       int64
 4   Comuna                     int64
 5   COMUNA                     object
 6   NOMBRE_REGION              object
 7   DIAG1                      object
 8   CAPITULO_DIAG1             object
 9   GLOSA_CAPITULO_DIAG1       object
 10  CODIGO_GRUPO_DIAG1         object
 11  GLOSA_GRUPO_DIAG1          object
 12  CODIGO_CATEGORIA_DIAG1     object
 13  GLOSA_CATEGORIA_DIAG1      object
 14  CODIGO_SUBCATEGORIA_DIAG1  object
 15  GLOSA_SUBCATEGORIA_DIAG1   object
 16  DIAG2                      object
 17  CAPITULO_DIAG2             object
 18  GLOSA_CAPITULO_DIAG2       object
 19  CODIGO_GRUPO_DIAG2         object
 20  GLOSA_GRUPO_DIAG2          object
 21  CODIGO_CATEGORIA_DIAG2     object
 22  GLOSA_CATEGORIA_DIAG2      object
 23  CODIGO_SUBCATEGORIA_DIAG2  object
 24  GLOSA_SUBCATEGORIA_DIAG2   object
 25  LUGAR_DEFUNCION            object
dtypes: int64(4), object(22)
memory usage: 354.5+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224208 entries, 0 to 224207
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Comuna      224208 non-null  int64
 1   Sexo        224208 non-null  int64
 2   Grupo_edad  224208 non-null  object
 3   Año         224208 non-null  int64
 4   Poblacion   224208 non-null  int64
dtypes: int64(4), object(1)
memory usage: 8.6+ MB

None

,Año,FECHA_DEF,Sexo,Edad,Comuna,COMUNA,NOMBRE_REGION,DIAG1,CAPITULO_DIAG1,GLOSA_CAPITULO_DIAG1,...,DIAG2,CAPITULO_DIAG2,GLOSA_CAPITULO_DIAG2,CODIGO_GRUPO_DIAG2,GLOSA_GRUPO_DIAG2,CODIGO_CATEGORIA_DIAG2,GLOSA_CATEGORIA_DIAG2,CODIGO_SUBCATEGORIA_DIAG2,GLOSA_SUBCATEGORIA_DIAG2,LUGAR_DEFUNCION
262,2015,2015-01-11,2,0,13127,Recoleta,Metropolitana de Santiago,T71X,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,W840,V01-Y98,Causas externas de morbilidad y de mortalidad,W75-W84,Otros accidentes que obstruyen la respración,W84,Obstrucción no especificada de la respiración,W840,OBSTRUCCIÓN NO ESPECIFICADA DE LA RESPIRACIÓN ...,Otro
374,2011,2011-09-15,1,29,1401,Pozo Almonte,De Tarapacá,S279,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,V853,V01-Y98,Causas externas de morbilidad y de mortalidad,V80-V89,Otros accidentes de transporte terrestre,V85,Ocupante de vehículo especial (de motor) para ...,V853,OCUPANTE NO ESPECIFICADO(A) DE VEHÍCULO ESPECI...,Otro
558,2009,2009-01-18,1,17,13127,Recoleta,Metropolitana de Santiago,S219,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,X990,V01-Y98,Causas externas de morbilidad y de mortalidad,X85-Y09,Agresiones,X99,Agresión con objeto cortante,X990,AGRESIÓN CON OBJETO CORTANTE OCURRIDA EN UNA V...,Otro
579,2016,2016-01-31,1,20,8203,Cañete,Del Bíobío,T751,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,W699,V01-Y98,Causas externas de morbilidad y de mortalidad,W65-W74,Ahogamiento y sumersión accidentales,W69,Ahogamiento y sumersión mientras se está en ag...,W699,AHOGAMIENTO Y SUMERSIÓN MIENTRAS SE ESTA EN AG...,Otro
596,2006,2006-01-17,1,50,13108,Independencia,Metropolitana de Santiago,T751,S00-T98,"Traumatismos, envenenamientos y algunas otras ...",...,W748,V01-Y98,Causas externas de morbilidad y de mortalidad,W65-W74,Ahogamiento y sumersión accidentales,W74,Ahogamiento y sumersión no especificados,W748,AHOGAMIENTO Y SUMERSIÓN NO ESPECIFICADOS OCURR...,Otro

   Comuna  Sexo       Grupo_edad   Año  Poblacion
0    1101     1            0 Año  2002       1469
1    1101     1    80 años y más  2002        604
2    1101     1    De 1 a 4 años  2002       5859
3    1101     1  De 10 a 14 años  2002       7570
4    1101     1  De 15 a 19 años  2002       7617

In [ ]:
# Filter for Cancer deaths
df_cancer_defunciones = df_defunciones[df_defunciones['CAPITULO_DIAG1'] == 'C00-D48'].copy()

# Filter for Gastric Cancer deaths
df_gastric_cancer_defunciones = df_defunciones[df_defunciones['CODIGO_CATEGORIA_DIAG1'] == 'C16'].copy()

display(df_cancer_defunciones.head())
display(df_gastric_cancer_defunciones.head())

,Año,FECHA_DEF,Sexo,Edad,Comuna,COMUNA,NOMBRE_REGION,DIAG1,CAPITULO_DIAG1,GLOSA_CAPITULO_DIAG1,...,DIAG2,CAPITULO_DIAG2,GLOSA_CAPITULO_DIAG2,CODIGO_GRUPO_DIAG2,GLOSA_GRUPO_DIAG2,CODIGO_CATEGORIA_DIAG2,GLOSA_CATEGORIA_DIAG2,CODIGO_SUBCATEGORIA_DIAG2,GLOSA_SUBCATEGORIA_DIAG2,LUGAR_DEFUNCION
544339,2004,2004-05-02,1,76,5801,Quilpué,De Valparaíso,C64X,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Casa habitación
544919,2004,2004-06-08,2,77,5801,Quilpué,De Valparaíso,C910,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Casa habitación
544920,2004,2004-03-01,1,78,9101,Temuco,De La Araucanía,C492,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Casa habitación
545281,2004,2004-01-01,1,79,13103,Cerro Navia,Metropolitana de Santiago,C61X,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Casa habitación
546192,2004,2004-12-17,1,77,9211,Victoria,De La Araucanía,C159,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Casa habitación

,Año,FECHA_DEF,Sexo,Edad,Comuna,COMUNA,NOMBRE_REGION,DIAG1,CAPITULO_DIAG1,GLOSA_CAPITULO_DIAG1,...,DIAG2,CAPITULO_DIAG2,GLOSA_CAPITULO_DIAG2,CODIGO_GRUPO_DIAG2,GLOSA_GRUPO_DIAG2,CODIGO_CATEGORIA_DIAG2,GLOSA_CATEGORIA_DIAG2,CODIGO_SUBCATEGORIA_DIAG2,GLOSA_SUBCATEGORIA_DIAG2,LUGAR_DEFUNCION
546472,2004,2004-12-28,1,80,13501,Melipilla,Metropolitana de Santiago,C169,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Casa habitación
575020,2008,2008-08-01,1,76,13114,Las Condes,Metropolitana de Santiago,C169,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Hospital o Clínica
575582,2005,2005-07-24,1,51,8304,Laja,Del Bíobío,C169,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Casa habitación
575815,2005,2005-09-15,2,35,8110,Talcahuano,Del Bíobío,C169,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Hospital o Clínica
575827,2007,2007-01-26,2,42,13122,Peñalolén,Metropolitana de Santiago,C169,C00-D48,Tumores [Neoplasias],...,None,None,None,None,None,None,None,None,None,Hospital o Clínica

#Calculo de tasas específicas y ajustadas por edad de la población

In [ ]:
# Filter for Cancer deaths with grouped ages
df_cancer_defunciones_grouped = df_defunciones[df_defunciones['CAPITULO_DIAG1'] == 'C00-D48'].copy()

# Filter for Gastric Cancer deaths with grouped ages
df_gastric_cancer_defunciones_grouped = df_defunciones[df_defunciones['CODIGO_CATEGORIA_DIAG1'] == 'C16'].copy()

# Define new age group bins and labels based on the requested grouping
# Group 0-19, 20-59, and 60+
new_age_bins = [-1, 19, 59, float('inf')]
new_age_labels = ['0-19', '20-59', '60+']


# Apply the new age grouping to the death dataframes using the 'Edad' column
df_cancer_defunciones_grouped['Edad_Grupo_Cancer'] = pd.cut(
    df_cancer_defunciones_grouped['Edad'],
    bins=new_age_bins,
    labels=new_age_labels,
    right=True,
    include_lowest=True
)

df_gastric_cancer_defunciones_grouped['Edad_Grupo_Cancer'] = pd.cut(
    df_gastric_cancer_defunciones_grouped['Edad'],
    bins=new_age_bins,
    labels=new_age_labels,
    right=True,
    include_lowest=True
)

# --- Age Grouping and Aggregation for Population Data ---
# Define a mapping for age groups to a numerical representation (e.g., lower bound of age group)
age_group_mapping = {
    '0 Año': 0,
    'De 1 a 4 años': 1,
    'De 5 a 9 años': 5,
    'De 10 a 14 años': 10,
    'De 15 a 19 años': 15,
    'De 20 a 24 años': 20,
    'De 25 a 29 años': 25,
    'De 30 a 34 años': 30,
    'De 35 a 39 años': 35,
    'De 40 a 44 años': 40,
    'De 45 a 49 años': 45,
    'De 50 a 54 años': 50,
    'De 55 a 59 años': 55,
    'De 60 a 64 años': 60,
    'De 65 a 69 años': 65,
    'De 70 a 74 años': 70,
    'De 75 a 79 años': 75,
    '80 años y más': 80
}

# Apply the mapping to create a new numerical age column
df_poblacion['Edad_Numerical_Approx'] = df_poblacion['Grupo_edad'].map(age_group_mapping)

# Apply the new age grouping to the population dataframe using the numerical approximation and new_age_labels
df_poblacion['Edad_Grupo_Cancer'] = pd.cut(
    df_poblacion['Edad_Numerical_Approx'],
    bins=new_age_bins,
    labels=new_age_labels,
    right=True,
    include_lowest=True
)

# Filter out any rows where the age group mapping resulted in NaN (if any)
df_poblacion_cleaned = df_poblacion.dropna(subset=['Edad_Grupo_Cancer']).copy()


# Aggregate population by Año, Comuna, Sexo, and Edad_Grupo_Cancer
df_poblacion_agg_cancer_grouped = df_poblacion_cleaned.groupby(['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'], observed=True)['Poblacion'].sum().reset_index()


# Aggregate deaths for Cancer by Año, Comuna, Sexo, and Edad_Grupo_Cancer
df_cancer_deaths_agg_cancer_grouped = df_cancer_defunciones_grouped.groupby(['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'], observed=True).size().reset_index(name='Cancer_Deaths')

# Aggregate deaths for Gastric Cancer by Año, Comuna, Sexo, and Edad_Grupo_Cancer
df_gastric_cancer_deaths_agg_cancer_grouped = df_gastric_cancer_defunciones_grouped.groupby(['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'], observed=True).size().reset_index(name='Gastric_Cancer_Deaths')


# Merge aggregated cancer deaths with new grouped population data
df_cancer_rates_age_specific_cancer_grouped = pd.merge(
    df_cancer_deaths_agg_cancer_grouped,
    df_poblacion_agg_cancer_grouped,
    on=['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'],
    how='left'
)

# Merge aggregated gastric cancer deaths with new grouped population data, using left merge from population to ensure all population groups are included
df_gastric_cancer_rates_age_specific_cancer_grouped = pd.merge(
    df_poblacion_agg_cancer_grouped,
    df_gastric_cancer_deaths_agg_cancer_grouped,
    on=['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'],
    how='left'
)


# Fill NaN values in Gastric_Cancer_Deaths with 0 after the merge
df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Deaths'] = df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Deaths'].fillna(0)

# Fill NaN population values with 0
df_cancer_rates_age_specific_cancer_grouped['Poblacion'] = df_cancer_rates_age_specific_cancer_grouped['Poblacion'].fillna(0)
df_gastric_cancer_rates_age_specific_cancer_grouped['Poblacion'] = df_gastric_cancer_rates_age_specific_cancer_grouped['Poblacion'].fillna(0)


# Calculate age-specific mortality rates for Cancer with new grouped ages
df_cancer_rates_age_specific_cancer_grouped['Cancer_Age_Specific_Rate'] = (
    df_cancer_rates_age_specific_cancer_grouped['Cancer_Deaths'] / df_cancer_rates_age_specific_cancer_grouped['Poblacion']
) * 100000

# Calculate age-specific mortality rates for Gastric Cancer with new grouped ages
df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Age_Specific_Rate'] = (
    df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Deaths'] / df_gastric_cancer_rates_age_specific_cancer_grouped['Poblacion']
) * 100000

# Replace infinite values with 0 in the rate columns
import numpy as np
df_cancer_rates_age_specific_cancer_grouped.replace([np.inf, -np.inf], 0, inplace=True)
df_gastric_cancer_rates_age_specific_cancer_grouped.replace([np.inf, -np.inf], 0, inplace=True)

# Fill NaN values in the rate columns with 0 after calculation
df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Age_Specific_Rate'] = df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Age_Specific_Rate'].fillna(0)


# --- Calculate Age-Adjusted Rates using National Population by new age groups as the standard ---

# Define the 2017 census population for the standard population by the new age groups
standard_population_2017 = {
    '0-19': 4768447,
    '20-59': 9955385,
    '60+': 2850171
}

# Create a DataFrame for the standard population distribution
df_standard_pop_dist = pd.DataFrame(list(standard_population_2017.items()), columns=['Edad_Grupo_Cancer', 'Standard_Population'])


# Calculate the total size of the standard population
total_standard_population = df_standard_pop_dist['Standard_Population'].sum()


# Merge age-specific cancer rates with the standard population distribution
df_cancer_rates_standardized = pd.merge(
    df_cancer_rates_age_specific_cancer_grouped,
    df_standard_pop_dist,
    on='Edad_Grupo_Cancer',
    how='left'
)

df_gastric_cancer_rates_standardized = pd.merge(
    df_gastric_cancer_rates_age_specific_cancer_grouped,
    df_standard_pop_dist,
    on='Edad_Grupo_Cancer',
    how='left'
)

# Calculate expected deaths in the standard population for each group
df_cancer_rates_standardized['Expected_Deaths_Standard_Pop'] = (
    df_cancer_rates_standardized['Cancer_Age_Specific_Rate'] / 100000
) * df_cancer_rates_standardized['Standard_Population']

df_gastric_cancer_rates_standardized['Expected_Deaths_Standard_Pop'] = (
    df_gastric_cancer_rates_standardized['Gastric_Cancer_Age_Specific_Rate'] / 100000
) * df_gastric_cancer_rates_standardized['Standard_Population']

# Fill NaN expected deaths with 0 after calculation
df_gastric_cancer_rates_standardized['Expected_Deaths_Standard_Pop'] = df_gastric_cancer_rates_standardized['Expected_Deaths_Standard_Pop'].fillna(0)


# Aggregate expected deaths by Año, Comuna, and Sexo to get total expected deaths in standard population
df_cancer_age_adjusted_rates = df_cancer_rates_standardized.groupby(['Año', 'Comuna', 'Sexo'])['Expected_Deaths_Standard_Pop'].sum().reset_index(name='Total_Expected_Deaths_Standard_Pop')
df_gastric_cancer_age_adjusted_rates = df_gastric_cancer_rates_standardized.groupby(['Año', 'Comuna', 'Sexo'])['Expected_Deaths_Standard_Pop'].sum().reset_index(name='Total_Expected_Deaths_Standard_Pop')


# Calculate the age-adjusted rate
# Ensure we are dividing by the total standard population
df_cancer_age_adjusted_rates['Cancer_Age_Adjusted_Rate'] = (
    df_cancer_age_adjusted_rates['Total_Expected_Deaths_Standard_Pop'] / total_standard_population
) * 100000

df_gastric_cancer_age_adjusted_rates['Gastric_Cancer_Age_Adjusted_Rate'] = (
    df_gastric_cancer_age_adjusted_rates['Total_Expected_Deaths_Standard_Pop'] / total_standard_population
) * 100000

# Fill NaN age-adjusted rates with 0 after calculation
df_gastric_cancer_age_adjusted_rates['Gastric_Cancer_Age_Adjusted_Rate'] = df_gastric_cancer_age_adjusted_rates['Gastric_Cancer_Age_Adjusted_Rate'].fillna(0)


# Display the resulting age-adjusted rates
display(df_cancer_age_adjusted_rates.head())
display(df_gastric_cancer_age_adjusted_rates.head())

# Display age-specific rates for Comuna 1405, Año 2002
print("\nAge-Specific Rates for Comuna 1405, Año 2002 (All Cancer):")
display(df_cancer_rates_age_specific_cancer_grouped[(df_cancer_rates_age_specific_cancer_grouped['Comuna'] == 1405) & (df_cancer_rates_age_specific_cancer_grouped['Año'] == 2002)])

print("\nAge-Specific Rates for Comuna 1405, Año 2002 (Gastric Cancer):")
display(df_gastric_cancer_rates_age_specific_cancer_grouped[(df_gastric_cancer_rates_age_specific_cancer_grouped['Comuna'] == 1405) & (df_gastric_cancer_rates_age_specific_cancer_grouped['Año'] == 2002)])

,Año,Comuna,Sexo,Total_Expected_Deaths_Standard_Pop,Cancer_Age_Adjusted_Rate
0,2002,1101,1,52819.597904,300.555303
1,2002,1101,2,34294.494045,195.143326
2,2002,1401,1,23702.045738,134.869931
3,2002,1401,2,13971.426471,79.500535
4,2002,1405,1,67666.168270,385.035602

,Año,Comuna,Sexo,Total_Expected_Deaths_Standard_Pop,Gastric_Cancer_Age_Adjusted_Rate
0,2002,1101,1,10150.175778,57.756766
1,2002,1101,2,2616.179973,14.886648
2,2002,1107,1,0.000000,0.000000
3,2002,1107,2,0.000000,0.000000
4,2002,1401,1,0.000000,0.000000

Age-Specific Rates for Comuna 1405, Año 2002 (All Cancer):

,Año,Comuna,Sexo,Edad_Grupo_Cancer,Cancer_Deaths,Poblacion,Cancer_Age_Specific_Rate
8,2002,1405,1,20-59,1,1048,95.419847
9,2002,1405,1,60+,5,245,2040.816327
10,2002,1405,2,20-59,1,843,118.623962

Age-Specific Rates for Comuna 1405, Año 2002 (Gastric Cancer):

,Año,Comuna,Sexo,Edad_Grupo_Cancer,Poblacion,Gastric_Cancer_Deaths,Gastric_Cancer_Age_Specific_Rate
36,2002,1405,1,0-19,617,0.0,0.0
37,2002,1405,1,20-59,1048,0.0,0.0
38,2002,1405,1,60+,245,0.0,0.0
39,2002,1405,2,0-19,587,0.0,0.0
40,2002,1405,2,20-59,843,0.0,0.0
41,2002,1405,2,60+,280,0.0,0.0

In [ ]:
# Calculate age-specific mortality rates for Cancer with new grouped ages
df_cancer_rates_age_specific_cancer_grouped['Cancer_Age_Specific_Rate'] = (
    df_cancer_rates_age_specific_cancer_grouped['Cancer_Deaths'] / df_cancer_rates_age_specific_cancer_grouped['Poblacion']
) * 100000

# Calculate age-specific mortality rates for Gastric Cancer with new grouped ages
df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Age_Specific_Rate'] = (
    df_gastric_cancer_rates_age_specific_cancer_grouped['Gastric_Cancer_Deaths'] / df_gastric_cancer_rates_age_specific_cancer_grouped['Poblacion']
) * 100000

# Replace infinite values with 0 in the rate columns
import numpy as np
df_cancer_rates_age_specific_cancer_grouped.replace([np.inf, -np.inf], 0, inplace=True)
df_gastric_cancer_rates_age_specific_cancer_grouped.replace([np.inf, -np.inf], 0, inplace=True)


# --- Calculate Age-Adjusted Rates using National Population by new age groups as the standard ---

# Define the 2017 census population for the standard population by the new age groups
standard_population_2017 = {
    '0-19': 4768447,
    '20-59': 9955385,
    '60+': 2850171
}

# Create a DataFrame for the standard population distribution
df_standard_pop_dist = pd.DataFrame(list(standard_population_2017.items()), columns=['Edad_Grupo_Cancer', 'Standard_Population'])


# Calculate the total size of the standard population
total_standard_population = df_standard_pop_dist['Standard_Population'].sum()


# Merge age-specific cancer rates with the standard population distribution
df_cancer_rates_standardized = pd.merge(
    df_cancer_rates_age_specific_cancer_grouped,
    df_standard_pop_dist,
    on='Edad_Grupo_Cancer',
    how='left'
)

df_gastric_cancer_rates_standardized = pd.merge(
    df_gastric_cancer_rates_age_specific_cancer_grouped,
    df_standard_pop_dist,
    on='Edad_Grupo_Cancer',
    how='left'
)

# Calculate expected deaths in the standard population for each group
df_cancer_rates_standardized['Expected_Deaths_Standard_Pop'] = (
    df_cancer_rates_standardized['Cancer_Age_Specific_Rate'] / 100000
) * df_cancer_rates_standardized['Standard_Population']

df_gastric_cancer_rates_standardized['Expected_Deaths_Standard_Pop'] = (
    df_gastric_cancer_rates_standardized['Gastric_Cancer_Age_Specific_Rate'] / 100000
) * df_gastric_cancer_rates_standardized['Standard_Population']


# Aggregate expected deaths by Año, Comuna, and Sexo to get total expected deaths in standard population
df_cancer_age_adjusted_rates = df_cancer_rates_standardized.groupby(['Año', 'Comuna', 'Sexo'])['Expected_Deaths_Standard_Pop'].sum().reset_index(name='Total_Expected_Deaths_Standard_Pop')
df_gastric_cancer_age_adjusted_rates = df_gastric_cancer_rates_standardized.groupby(['Año', 'Comuna', 'Sexo'])['Expected_Deaths_Standard_Pop'].sum().reset_index(name='Total_Expected_Deaths_Standard_Pop')


# Calculate the age-adjusted rate
# Ensure we are dividing by the total standard population
df_cancer_age_adjusted_rates['Cancer_Age_Adjusted_Rate'] = (
    df_cancer_age_adjusted_rates['Total_Expected_Deaths_Standard_Pop'] / total_standard_population
) * 100000

df_gastric_cancer_age_adjusted_rates['Gastric_Cancer_Age_Adjusted_Rate'] = (
    df_gastric_cancer_age_adjusted_rates['Total_Expected_Deaths_Standard_Pop'] / total_standard_population
) * 100000


# Display the resulting age-adjusted rates
display(df_cancer_age_adjusted_rates.head())
display(df_gastric_cancer_age_adjusted_rates.head())

,Año,Comuna,Sexo,Total_Expected_Deaths_Standard_Pop,Cancer_Age_Adjusted_Rate
0,2002,1101,1,52819.597904,300.555303
1,2002,1101,2,34294.494045,195.143326
2,2002,1401,1,23702.045738,134.869931
3,2002,1401,2,13971.426471,79.500535
4,2002,1405,1,67666.168270,385.035602

,Año,Comuna,Sexo,Total_Expected_Deaths_Standard_Pop,Gastric_Cancer_Age_Adjusted_Rate
0,2002,1101,1,10150.175778,57.756766
1,2002,1101,2,2616.179973,14.886648
2,2002,1107,1,0.000000,0.000000
3,2002,1107,2,0.000000,0.000000
4,2002,1401,1,0.000000,0.000000

# Calculo de las defunciones por causas específicas

In [ ]:
# Calculate absolute cancer deaths per commune and year (without sex disaggregation)
df_cancer_absolute_deaths_comuna_year = df_cancer_defunciones_grouped.groupby(['Año', 'Comuna']).size().reset_index(name='Absolute_Cancer_Deaths')

# Calculate absolute gastric cancer deaths per commune and year (without sex disaggregation)
df_gastric_cancer_absolute_deaths_comuna_year = df_gastric_cancer_defunciones_grouped.groupby(['Año', 'Comuna']).size().reset_index(name='Absolute_Gastric_Cancer_Deaths')

# Display the results
display(df_cancer_absolute_deaths_comuna_year.head())
display(df_gastric_cancer_absolute_deaths_comuna_year.head())

    Año  Comuna  Absolute_Cancer_Deaths
0  2002    1101                     272
1  2002    1401                       6
2  2002    1405                       7
3  2002    2101                     488
4  2002    2102                       9

    Año  Comuna  Absolute_Gastric_Cancer_Deaths
0  2002    1101                              38
1  2002    2101                              34
2  2002    2102                               1
3  2002    2104                               2
4  2002    2201                              14

# Calculo de las tasas por causas específicas ajustadas por edad

In [ ]:
# Filter for Cancer deaths with grouped ages (without sex disaggregation)
# Using the already filtered dataframes from cell 6d061582
df_cancer_defunciones_grouped_no_sex = df_cancer_defunciones_grouped.copy()
df_gastric_cancer_defunciones_grouped_no_sex = df_gastric_cancer_defunciones_grouped.copy()

# The 'Edad_Grupo_Cancer' column was added to df_poblacion_cleaned in cell 6d061582.
# We will use df_poblacion_cleaned for the population aggregation without sex disaggregation.


# Aggregate deaths for Cancer by Año, Comuna, and Edad_Grupo_Cancer (without sex disaggregation)
df_cancer_deaths_agg_cancer_grouped_no_sex = df_cancer_defunciones_grouped_no_sex.groupby(['Año', 'Comuna', 'Edad_Grupo_Cancer'], observed=True).size().reset_index(name='Cancer_Deaths')

# Aggregate deaths for Gastric Cancer by Año, Comuna, and Edad_Grupo_Cancer (without sex disaggregation)
df_gastric_cancer_deaths_agg_cancer_grouped_no_sex = df_gastric_cancer_defunciones_grouped_no_sex.groupby(['Año', 'Comuna', 'Edad_Grupo_Cancer'], observed=True).size().reset_index(name='Gastric_Cancer_Deaths')

# Aggregate population by Año, Comuna, and Edad_Grupo_Cancer (without sex disaggregation)
# Use df_poblacion_cleaned which already has the 'Edad_Grupo_Cancer' column
df_poblacion_agg_cancer_grouped_no_sex = df_poblacion_cleaned.groupby(['Año', 'Comuna', 'Edad_Grupo_Cancer'], observed=True)['Poblacion'].sum().reset_index()


# Merge aggregated cancer deaths with new grouped population data (without sex disaggregation)
df_cancer_rates_age_specific_cancer_grouped_no_sex = pd.merge(
    df_cancer_deaths_agg_cancer_grouped_no_sex,
    df_poblacion_agg_cancer_grouped_no_sex,
    on=['Año', 'Comuna', 'Edad_Grupo_Cancer'],
    how='left'
)

# Merge aggregated gastric cancer deaths with new grouped population data (without sex disaggregation)
df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex = pd.merge(
    df_gastric_cancer_deaths_agg_cancer_grouped_no_sex,
    df_poblacion_agg_cancer_grouped_no_sex,
    on=['Año', 'Comuna', 'Edad_Grupo_Cancer'],
    how='left'
)

# Fill NaN population values with 0
df_cancer_rates_age_specific_cancer_grouped_no_sex['Poblacion'] = df_cancer_rates_age_specific_cancer_grouped_no_sex['Poblacion'].fillna(0)
df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex['Poblacion'] = df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex['Poblacion'].fillna(0)

# Calculate age-specific mortality rates for Cancer with new grouped ages (without sex disaggregation)
df_cancer_rates_age_specific_cancer_grouped_no_sex['Cancer_Age_Specific_Rate'] = (
    df_cancer_rates_age_specific_cancer_grouped_no_sex['Cancer_Deaths'] / df_cancer_rates_age_specific_cancer_grouped_no_sex['Poblacion']
) * 100000

# Calculate age-specific mortality rates for Gastric Cancer with new grouped ages (without sex disaggregation)
df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex['Gastric_Cancer_Age_Specific_Rate'] = (
    df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex['Gastric_Cancer_Deaths'] / df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex['Poblacion']
) * 100000

# Replace infinite values with 0 in the rate columns
import numpy as np
df_cancer_rates_age_specific_cancer_grouped_no_sex.replace([np.inf, -np.inf], 0, inplace=True)
df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex.replace([np.inf, -np.inf], 0, inplace=True)


# --- Calculate Age-Adjusted Rates using National Population by new age groups as the standard (without sex disaggregation) ---

# Use the standard population distribution (2017 Census) calculated in cell 6d061582
# df_standard_pop_dist variable is available from the execution of cell 6d061582
# total_standard_population is also available from the execution of cell 6d061582


# Merge age-specific cancer rates with the standard population distribution (without sex disaggregation)
df_cancer_rates_standardized_no_sex = pd.merge(
    df_cancer_rates_age_specific_cancer_grouped_no_sex,
    df_standard_pop_dist, # Use the standard population calculated previously
    on='Edad_Grupo_Cancer',
    how='left'
)

df_gastric_cancer_rates_standardized_no_sex = pd.merge(
    df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex,
    df_standard_pop_dist, # Use the standard population calculated previously
    on='Edad_Grupo_Cancer',
    how='left'
)

# Calculate expected deaths in the standard population for each group (without sex disaggregation)
df_cancer_rates_standardized_no_sex['Expected_Deaths_Standard_Pop'] = (
    df_cancer_rates_standardized_no_sex['Cancer_Age_Specific_Rate'] / 100000
) * df_cancer_rates_standardized_no_sex['Standard_Population']

df_gastric_cancer_rates_standardized_no_sex['Expected_Deaths_Standard_Pop'] = (
    df_gastric_cancer_rates_standardized_no_sex['Gastric_Cancer_Age_Specific_Rate'] / 100000
) * df_gastric_cancer_rates_standardized_no_sex['Standard_Population']


# Aggregate expected deaths by Año and Comuna to get total expected deaths in standard population (without sex disaggregation)
df_cancer_age_adjusted_rates_no_sex = df_cancer_rates_standardized_no_sex.groupby(['Año', 'Comuna'])['Expected_Deaths_Standard_Pop'].sum().reset_index(name='Total_Expected_Deaths_Standard_Pop')
df_gastric_cancer_age_adjusted_rates_no_sex = df_gastric_cancer_rates_standardized_no_sex.groupby(['Año', 'Comuna'])['Expected_Deaths_Standard_Pop'].sum().reset_index(name='Total_Expected_Deaths_Standard_Pop')


# Calculate the age-adjusted rate (without sex disaggregation)
# Ensure we are dividing by the total standard population
# total_standard_population was calculated in cell 6d061582
df_cancer_age_adjusted_rates_no_sex['Cancer_Age_Adjusted_Rate'] = (
    df_cancer_age_adjusted_rates_no_sex['Total_Expected_Deaths_Standard_Pop'] / total_standard_population
) * 100000

df_gastric_cancer_age_adjusted_rates_no_sex['Gastric_Cancer_Age_Adjusted_Rate'] = (
    df_gastric_cancer_age_adjusted_rates_no_sex['Total_Expected_Deaths_Standard_Pop'] / total_standard_population
) * 100000


# Display the resulting age-adjusted rates (without sex disaggregation)
display(df_cancer_rates_age_specific_cancer_grouped_no_sex.head(20)) # Display intermediate age-specific rates for all cancer
display(df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex.head(20)) # Display intermediate age-specific rates for gastric cancer
display(df_cancer_age_adjusted_rates_no_sex.head(20))
display(df_gastric_cancer_age_adjusted_rates_no_sex.head(20))

,Año,Comuna,Edad_Grupo_Cancer,Cancer_Deaths,Poblacion,Cancer_Age_Specific_Rate
0,2002,1101,0-19,5,58777,8.506729
1,2002,1101,20-59,72,98749,72.912131
2,2002,1101,60+,195,16085,1212.309605
3,2002,1401,60+,6,889,674.915636
4,2002,1405,20-59,2,1891,105.764146
5,2002,1405,60+,5,525,952.380952
6,2002,2101,0-19,9,106734,8.432177
7,2002,2101,20-59,122,165438,73.743638
8,2002,2101,60+,357,28131,1269.062600
9,2002,2102,20-59,4,4585,87.241003
10,2002,2102,60+,5,619,807.754443
11,2002,2104,0-19,1,4045,24.721879
12,2002,2104,20-59,5,5519,90.596122
13,2002,2104,60+,19,1147,1656.495205
14,2002,2201,0-19,2,55262,3.619123
15,2002,2201,20-59,30,77508,38.705682
16,2002,2201,60+,70,9441,741.446881
17,2002,2301,0-19,1,9133,10.949305
18,2002,2301,20-59,10,12748,78.443677
19,2002,2301,60+,36,2939,1224.906431

,Año,Comuna,Edad_Grupo_Cancer,Gastric_Cancer_Deaths,Poblacion,Gastric_Cancer_Age_Specific_Rate
0,2002,1101,20-59,11,98749,11.139353
1,2002,1101,60+,27,16085,167.858253
2,2002,2101,20-59,8,165438,4.835648
3,2002,2101,60+,26,28131,92.424727
4,2002,2102,60+,1,619,161.550889
5,2002,2104,20-59,1,5519,18.119224
6,2002,2104,60+,1,1147,87.183958
7,2002,2201,20-59,3,77508,3.870568
8,2002,2201,60+,11,9441,116.513081
9,2002,2301,60+,3,2939,102.075536
10,2002,2302,60+,2,425,470.588235
11,2002,3101,60+,18,12095,148.821827
12,2002,3102,60+,2,1279,156.372166
13,2002,3201,20-59,3,6958,43.115838
14,2002,3201,60+,2,1560,128.205128
15,2002,3202,60+,4,1343,297.840655
16,2002,3301,20-59,1,25171,3.972826
17,2002,3301,60+,9,5886,152.905199
18,2002,3302,60+,2,859,232.828871
19,2002,3303,20-59,1,2924,34.199726

     Año  Comuna  Total_Expected_Deaths_Standard_Pop  Cancer_Age_Adjusted_Rate
0   2002    1101                        42217.218982                240.225400
1   2002    1401                        19236.249719                109.458555
2   2002    1405                        37673.713636                214.371840
3   2002    2101                        43914.001182                249.880469
4   2002    2102                        31707.560629                180.423098
5   2002    2104                        57410.988425                326.681340
6   2002    2201                        25158.379615                143.156796
7   2002    2301                        43243.409756                246.064654
8   2002    2302                        28461.192234                161.950537
9   2002    3101                        31801.081720                180.955254
10  2002    3102                         8913.748241                 50.721217
11  2002    3103                        22753.563460                129.472855
12  2002    3201                        29078.305070                165.462047
13  2002    3202                        17774.813015                101.142654
14  2002    3301                        32435.884410                184.567423
15  2002    3302                        19908.062864                113.281322
16  2002    3303                        38346.590690                218.200661
17  2002    3304                        21349.122729                121.481274
18  2002    4101                        31589.151017                179.749321
19  2002    4102                        30166.542248                171.654359

,Año,Comuna,Total_Expected_Deaths_Standard_Pop,Gastric_Cancer_Age_Adjusted_Rate
0,2002,1101,5893.212758,33.533696
1,2002,2101,3115.670186,17.728859
2,2002,2102,4604.476575,26.200500
3,2002,2104,4288.730450,24.403834
4,2002,2201,3706.152019,21.088832
5,2002,2301,2909.327322,16.554722
6,2002,2302,13412.569412,76.320514
7,2002,3101,4241.676561,24.136086
8,2002,3102,4456.874120,25.360609
9,2002,3201,7946.413042,45.216864
10,2002,3202,8488.967982,48.304123
11,2002,3301,4753.569744,27.048873
12,2002,3302,6636.020955,37.760441
13,2002,3303,11289.004889,64.236958
14,2002,3304,2853.024024,16.234344
15,2002,4101,4612.210791,26.244509
16,2002,4102,4467.640662,25.421873
17,2002,4103,1785.821429,10.161723
18,2002,4105,8961.838887,50.994864
19,2002,4106,4571.183789,26.011056

# Summary of Calculated Mortality Rates and DataFrames

Here is a summary of the different mortality rates calculated and the pandas DataFrames where they are stored:

1.  **Age-Adjusted Rates for All Cancers (by Year, Commune, and Sex):**
    *   DataFrame: `df_cancer_age_adjusted_rates`
    *   Contains the age-adjusted mortality rate for all cancers, allowing comparison across years and communes while accounting for age differences, broken down by sex.

2.  **Age-Adjusted Rates for Gastric Cancer (by Year, Commune, and Sex):**
    *   DataFrame: `df_gastric_cancer_age_adjusted_rates`
    *   Contains the age-adjusted mortality rate for gastric cancer, disaggregated by sex.

3.  **Age-Adjusted Rates for All Cancers (by Year and Commune, without Sex Disaggregation):**
    *   DataFrame: `df_cancer_age_adjusted_rates_no_sex`
    *   Contains the age-adjusted rate for all cancers for the combined sexes, useful for comparing the overall burden across communes and years without the sex breakdown.

4.  **Age-Adjusted Rates for Gastric Cancer (by Year and Commune, without Sex Disaggregation):**
    *   DataFrame: `df_gastric_cancer_age_adjusted_rates_no_sex`
    *   Contains the age-adjusted rate for gastric cancer for the combined sexes.

5.  **Age-Specific Rates for All Cancers (by Year, Commune, Sex, and Cancer Age Group):**
    *   DataFrame: `df_cancer_rates_age_specific_cancer_grouped`
    *   Contains the age-specific rates for all cancers for each specific age group within each year, commune, and sex.

6.  **Age-Specific Rates for Gastric Cancer (by Year, Commune, Sex, and Cancer Age Group):**
    *   DataFrame: `df_gastric_cancer_rates_age_specific_cancer_grouped`
    *   Contains the age-specific rates for gastric cancer, by year, commune, sex, and age group.

7.  **Age-Specific Rates for All Cancers (by Year, Commune, and Cancer Age Group, without Sex Disaggregation):**
    *   DataFrame: `df_cancer_rates_age_specific_cancer_grouped_no_sex`
    *   Contains the age-specific rates for all cancers for the combined sexes, by year, commune, and age group.

8.  **Age-Specific Rates for Gastric Cancer (by Year, Commune, and Cancer Age Group, without Sex Disaggregation):**
    *   DataFrame: `df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex`
    *   Contains the age-specific rates for gastric cancer for the combined sexes, by year, commune, and age group.

#Guardar dataframes intermedios

In [ ]:
# Save the intermediate dataframes used for final combinations to parquet files
output_dir = path_tasas

# Dataframes used in cell 87f42b7c to create df_combined_final:
# df_cancer_rates_age_specific_cancer_grouped
# df_gastric_cancer_rates_age_specific_cancer_grouped
# df_cancer_rates_standardized
# df_gastric_cancer_rates_standardized
# df_poblacion_agg_cancer_grouped (used to calculate total population)
# df_crude_rates_calculated (calculated using intermediate dataframes and used in the final merge)
# df_cancer_age_adjusted_rates
# df_gastric_cancer_age_adjusted_rates


# Dataframes used in cell a4af0c5a to create df_combined_final_no_sex:
# df_cancer_rates_age_specific_cancer_grouped_no_sex
# df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex
# df_cancer_rates_standardized_no_sex
# df_gastric_cancer_rates_standardized_no_sex
# df_crude_rates_calculated (already listed above)
# df_cancer_age_adjusted_rates_no_sex
# df_gastric_cancer_age_adjusted_rates_no_sex
# df_poblacion_agg_cancer_grouped_no_sex (used to calculate total population, derived from df_poblacion_cleaned in 6d061582 which is aggregated in 6d061582)

# Calculate total population by Año and Comuna
df_total_population_comuna_year = df_poblacion_agg_cancer_grouped.groupby(['Año', 'Comuna'])['Poblacion'].sum().reset_index(name='Total_Population')

# Calculate total deaths for all cancer by Año and Comuna
df_cancer_total_deaths_comuna_year = df_cancer_defunciones_grouped.groupby(['Año', 'Comuna']).size().reset_index(name='Total_Cancer_Deaths')

# Calculate total deaths for gastric cancer by Año and Comuna
df_gastric_cancer_total_deaths_comuna_year = df_gastric_cancer_defunciones_grouped.groupby(['Año', 'Comuna']).size().reset_index(name='Total_Gastric_Cancer_Deaths')


# Merge total population and total deaths for crude rate calculation
df_crude_rates_calculated = pd.merge(
    df_total_population_comuna_year,
    df_cancer_total_deaths_comuna_year,
    on=['Año', 'Comuna'],
    how='left'
)

df_crude_rates_calculated = pd.merge(
    df_crude_rates_calculated,
    df_gastric_cancer_total_deaths_comuna_year,
    on=['Año', 'Comuna'],
    how='left'
)

# Fill NaN death values with 0
df_crude_rates_calculated['Total_Cancer_Deaths'] = df_crude_rates_calculated['Total_Cancer_Deaths'].fillna(0)
df_crude_rates_calculated['Total_Gastric_Cancer_Deaths'] = df_crude_rates_calculated['Total_Gastric_Cancer_Deaths'].fillna(0)


# Calculate crude rate for all cancer
df_crude_rates_calculated['Cancer_Crude_Rate'] = (
    df_crude_rates_calculated['Total_Cancer_Deaths'] / df_crude_rates_calculated['Total_Population']
) * 100000

# Calculate crude rate for gastric cancer
df_crude_rates_calculated['Gastric_Cancer_Crude_Rate'] = (
    df_crude_rates_calculated['Total_Gastric_Cancer_Deaths'] / df_crude_rates_calculated['Total_Population']
) * 100000

# Replace infinite values with 0 in the calculated crude rate columns
import numpy as np
df_crude_rates_calculated.replace([np.inf, -np.inf], 0, inplace=True)

# Saving the relevant intermediate dataframes:
df_cancer_rates_age_specific_cancer_grouped.to_parquet(f'{output_dir}Cancer_Age_Specific_Rates_Grouped.parquet', index=False)
df_gastric_cancer_rates_age_specific_cancer_grouped.to_parquet(f'{output_dir}Gastric_Cancer_Age_Specific_Rates_Grouped.parquet', index=False)
df_cancer_rates_standardized.to_parquet(f'{output_dir}Cancer_Rates_Standardized.parquet', index=False)
df_gastric_cancer_rates_standardized.to_parquet(f'{output_dir}Gastric_Cancer_Rates_Standardized.parquet', index=False)
df_poblacion_agg_cancer_grouped.to_parquet(f'{output_dir}Population_Agg_Cancer_Grouped.parquet', index=False)
df_crude_rates_calculated.to_parquet(f'{output_dir}Crude_Rates_Calculated.parquet', index=False)
df_cancer_age_adjusted_rates.to_parquet(f'{output_dir}Cancer_Age_Adjusted_Rates.parquet', index=False)
df_gastric_cancer_age_adjusted_rates.to_parquet(f'{output_dir}Gastric_Cancer_Age_Adjusted_Rates.parquet', index=False)
df_cancer_rates_age_specific_cancer_grouped_no_sex.to_parquet(f'{output_dir}Cancer_Age_Specific_Rates_Grouped_No_Sex.parquet', index=False)
df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex.to_parquet(f'{output_dir}Gastric_Cancer_Age_Specific_Rates_Grouped_No_Sex.parquet', index=False)
df_cancer_rates_standardized_no_sex.to_parquet(f'{output_dir}Cancer_Rates_Standardized_No_Sex.parquet', index=False)
df_gastric_cancer_rates_standardized_no_sex.to_parquet(f'{output_dir}Gastric_Cancer_Rates_Standardized_No_Sex.parquet', index=False)
df_cancer_age_adjusted_rates_no_sex.to_parquet(f'{output_dir}Cancer_Age_Adjusted_Rates_No_Sex.parquet', index=False)
df_gastric_cancer_age_adjusted_rates_no_sex.to_parquet(f'{output_dir}Gastric_Cancer_Age_Adjusted_Rates_No_Sex.parquet', index=False)
df_poblacion_agg_cancer_grouped_no_sex.to_parquet(f'{output_dir}Population_Agg_Cancer_Grouped_No_Sex.parquet', index=False)


print(f"Saved intermediate dataframes to {output_dir}")

Saved intermediate dataframes to /content/drive/MyDrive/DSP 2025-1/cursos/PHDMISP2 Métodos de investigación en salud pública/seminario/Trabajo seminario/4 Tasas y razones de mortalidad/

#Generar dataframe combinado desagregado por sexo

In [ ]:
# Merge age-specific rates for all cancer and gastric cancer
df_combined_rates = pd.merge(
    df_cancer_rates_age_specific_cancer_grouped,
    df_gastric_cancer_rates_age_specific_cancer_grouped[['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer', 'Gastric_Cancer_Deaths', 'Gastric_Cancer_Age_Specific_Rate']],
    on=['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'],
    how='left'
)

# Fill NaN values in Gastric_Cancer_Deaths and Gastric_Cancer_Age_Specific_Rate with 0 after the initial merge
df_combined_rates['Gastric_Cancer_Deaths'] = df_combined_rates['Gastric_Cancer_Deaths'].fillna(0)
df_combined_rates['Gastric_Cancer_Age_Specific_Rate'] = df_combined_rates['Gastric_Cancer_Age_Specific_Rate'].fillna(0)


# Merge with standard population and expected deaths for cancer
df_combined_rates = pd.merge(
    df_combined_rates,
    df_cancer_rates_standardized[['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer', 'Standard_Population', 'Expected_Deaths_Standard_Pop']],
    on=['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'],
    how='left'
)

# Merge with expected deaths for gastric cancer
df_combined_rates = pd.merge(
    df_combined_rates,
    df_gastric_cancer_rates_standardized[['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer', 'Expected_Deaths_Standard_Pop']],
    on=['Año', 'Comuna', 'Sexo', 'Edad_Grupo_Cancer'],
    how='left',
    suffixes=('_Cancer', '_Gastric_Cancer') # Add suffixes to differentiate expected deaths columns
)

# Fill NaN values in the expected gastric cancer deaths column after the merge
df_combined_rates['Expected_Deaths_Standard_Pop_Gastric_Cancer'] = df_combined_rates['Expected_Deaths_Standard_Pop_Gastric_Cancer'].fillna(0)


# Calculate total population by Año and Comuna
df_total_population_comuna_year = df_poblacion_agg_cancer_grouped.groupby(['Año', 'Comuna'])['Poblacion'].sum().reset_index(name='Total_Population')

# Calculate total deaths for all cancer by Año and Comuna
df_cancer_total_deaths_comuna_year = df_combined_rates.groupby(['Año', 'Comuna'])['Cancer_Deaths'].sum().reset_index(name='Total_Cancer_Deaths')

# Calculate total deaths for gastric cancer by Año and Comuna
df_gastric_cancer_total_deaths_comuna_year = df_combined_rates.groupby(['Año', 'Comuna'])['Gastric_Cancer_Deaths'].sum().reset_index(name='Total_Gastric_Cancer_Deaths')


# Merge total population and total deaths for crude rate calculation
df_crude_rates_calculated = pd.merge(
    df_total_population_comuna_year,
    df_cancer_total_deaths_comuna_year,
    on=['Año', 'Comuna'],
    how='left'
)

df_crude_rates_calculated = pd.merge(
    df_crude_rates_calculated,
    df_gastric_cancer_total_deaths_comuna_year,
    on=['Año', 'Comuna'],
    how='left'
)

# Fill NaN death values with 0
df_crude_rates_calculated['Total_Cancer_Deaths'] = df_crude_rates_calculated['Total_Cancer_Deaths'].fillna(0)
df_crude_rates_calculated['Total_Gastric_Cancer_Deaths'] = df_crude_rates_calculated['Total_Gastric_Cancer_Deaths'].fillna(0)


# Calculate crude rate for all cancer
df_crude_rates_calculated['Cancer_Crude_Rate'] = (
    df_crude_rates_calculated['Total_Cancer_Deaths'] / df_crude_rates_calculated['Total_Population']
) * 100000

# Calculate crude rate for gastric cancer
df_crude_rates_calculated['Gastric_Cancer_Crude_Rate'] = (
    df_crude_rates_calculated['Total_Gastric_Cancer_Deaths'] / df_crude_rates_calculated['Total_Population']
) * 100000

# Replace infinite values with 0 in the calculated crude rate columns
df_crude_rates_calculated.replace([np.inf, -np.inf], 0, inplace=True)


# Merge the calculated crude rates back into the combined dataframe
# We need to merge based on Año and Comuna, and then propagate the rate to all rows within that group
df_combined_rates = pd.merge(
    df_combined_rates,
    df_crude_rates_calculated[['Año', 'Comuna', 'Cancer_Crude_Rate', 'Gastric_Cancer_Crude_Rate']],
    on=['Año', 'Comuna'],
    how='left'
)


# Merge with age-adjusted communal rates for all cancer
df_combined_rates = pd.merge(
    df_combined_rates,
    df_cancer_age_adjusted_rates[['Año', 'Comuna', 'Sexo', 'Cancer_Age_Adjusted_Rate']],
    on=['Año', 'Comuna', 'Sexo'],
    how='left'
)

# Merge with age-adjusted communal rates for gastric cancer
df_combined_rates = pd.merge(
    df_combined_rates,
    df_gastric_cancer_age_adjusted_rates[['Año', 'Comuna', 'Sexo', 'Gastric_Cancer_Age_Adjusted_Rate']],
    on=['Año', 'Comuna', 'Sexo'],
    how='left'
)

# Fill NaN values in Age_Adjusted_Rate columns with 0 after the merge
df_combined_rates['Cancer_Age_Adjusted_Rate'] = df_combined_rates['Cancer_Age_Adjusted_Rate'].fillna(0)
df_combined_rates['Gastric_Cancer_Age_Adjusted_Rate'] = df_combined_rates['Gastric_Cancer_Age_Adjusted_Rate'].fillna(0)


# Rename the Expected_Deaths_Standard_Pop columns for clarity
df_combined_rates.rename(columns={
    'Expected_Deaths_Standard_Pop_Cancer': 'Expected_Deaths_Cancer_Standard_Pop',
    'Expected_Deaths_Standard_Pop_Gastric_Cancer': 'Expected_Deaths_Gastric_Cancer_Standard_Pop'
}, inplace=True)


# Select and reorder columns to match the requested order
# Update column selection to include separate crude rates and remove the old 'Crude_Rate'
df_combined_final = df_combined_rates[[
    'Año',
    'Comuna',
    'Sexo',
    'Edad_Grupo_Cancer',
    'Poblacion',
    'Cancer_Deaths',
    'Gastric_Cancer_Deaths',
    'Cancer_Age_Specific_Rate',
    'Gastric_Cancer_Age_Specific_Rate',
    'Standard_Population',
    'Expected_Deaths_Cancer_Standard_Pop',
    'Expected_Deaths_Gastric_Cancer_Standard_Pop',
    'Cancer_Crude_Rate',        # Added Cancer Crude Rate
    'Gastric_Cancer_Crude_Rate',  # Added Gastric Cancer Crude Rate
    'Cancer_Age_Adjusted_Rate',
    'Gastric_Cancer_Age_Adjusted_Rate'
]]

# Display the head of the new combined dataframe
display(df_combined_final.head())

,Año,Comuna,Sexo,Edad_Grupo_Cancer,Poblacion,Cancer_Deaths,Gastric_Cancer_Deaths,Cancer_Age_Specific_Rate,Gastric_Cancer_Age_Specific_Rate,Standard_Population,Expected_Deaths_Cancer_Standard_Pop,Expected_Deaths_Gastric_Cancer_Standard_Pop,Cancer_Crude_Rate,Gastric_Cancer_Crude_Rate,Cancer_Age_Adjusted_Rate,Gastric_Cancer_Age_Adjusted_Rate
0,2002,1101,1,0-19,29982,3,0.0,10.006004,0.000000,4768447,477.130979,0.000000,156.6721,21.888014,300.555303,57.756766
1,2002,1101,1,20-59,51419,34,6.0,66.123417,11.668838,9955385,6582.840779,1161.677784,156.6721,21.888014,300.555303,57.756766
2,2002,1101,1,60+,6976,112,22.0,1605.504587,315.366972,2850171,45759.626147,8988.497993,156.6721,21.888014,300.555303,57.756766
3,2002,1101,2,0-19,28795,2,0.0,6.945650,0.000000,4768447,331.199653,0.000000,156.6721,21.888014,195.143326,14.886648
4,2002,1101,2,20-59,47330,38,5.0,80.287344,10.564124,9955385,7992.914219,1051.699239,156.6721,21.888014,195.143326,14.886648

#Generar dataframe combinado SIN dessagregación por sexo

In [ ]:
# Merge age-specific rates for all cancer and gastric cancer (without sex disaggregation)
df_combined_rates_no_sex = pd.merge(
    df_cancer_rates_age_specific_cancer_grouped_no_sex,
    df_gastric_cancer_rates_age_specific_cancer_grouped_no_sex[['Año', 'Comuna', 'Edad_Grupo_Cancer', 'Gastric_Cancer_Deaths', 'Gastric_Cancer_Age_Specific_Rate']],
    on=['Año', 'Comuna', 'Edad_Grupo_Cancer'],
    how='left'
)

# Merge with standard population and expected deaths for cancer (without sex disaggregation)
# Note: df_standard_pop_dist is not sex-specific, so it can be used directly
df_combined_rates_no_sex = pd.merge(
    df_combined_rates_no_sex,
    df_cancer_rates_standardized_no_sex[['Año', 'Comuna', 'Edad_Grupo_Cancer', 'Standard_Population', 'Expected_Deaths_Standard_Pop']],
    on=['Año', 'Comuna', 'Edad_Grupo_Cancer'],
    how='left'
)

# Merge with expected deaths for gastric cancer (without sex disaggregation)
df_combined_rates_no_sex = pd.merge(
    df_combined_rates_no_sex,
    df_gastric_cancer_rates_standardized_no_sex[['Año', 'Comuna', 'Edad_Grupo_Cancer', 'Expected_Deaths_Standard_Pop']],
    on=['Año', 'Comuna', 'Edad_Grupo_Cancer'],
    how='left',
    suffixes=('_Cancer', '_Gastric_Cancer') # Add suffixes to differentiate expected deaths columns
)


# Use the previously calculated crude rates without sex disaggregation from df_crude_rates_calculated
# Merge the calculated crude rates back into the combined dataframe (without sex disaggregation)
# We need to merge based on Año and Comuna, and then propagate the rate to all rows within that group
df_combined_rates_no_sex = pd.merge(
    df_combined_rates_no_sex,
    df_crude_rates_calculated[['Año', 'Comuna', 'Cancer_Crude_Rate', 'Gastric_Cancer_Crude_Rate']],
    on=['Año', 'Comuna'],
    how='left'
)


# Merge with age-adjusted communal rates for all cancer (without sex disaggregation)
df_combined_rates_no_sex = pd.merge(
    df_combined_rates_no_sex,
    df_cancer_age_adjusted_rates_no_sex[['Año', 'Comuna', 'Cancer_Age_Adjusted_Rate']],
    on=['Año', 'Comuna'],
    how='left'
)

# Merge with age-adjusted communal rates for gastric cancer (without sex disaggregation)
df_combined_rates_no_sex = pd.merge(
    df_combined_rates_no_sex,
    df_gastric_cancer_age_adjusted_rates_no_sex[['Año', 'Comuna', 'Gastric_Cancer_Age_Adjusted_Rate']],
    on=['Año', 'Comuna'],
    how='left'
)

# Rename the Expected_Deaths_Standard_Pop columns for clarity
df_combined_rates_no_sex.rename(columns={
    'Expected_Deaths_Standard_Pop_Cancer': 'Expected_Deaths_Cancer_Standard_Pop',
    'Expected_Deaths_Standard_Pop_Gastric_Cancer': 'Expected_Deaths_Gastric_Cancer_Standard_Pop'
}, inplace=True)

# Fill any remaining NaN values in the relevant columns with 0 after all merges
df_combined_rates_no_sex['Gastric_Cancer_Deaths'] = df_combined_rates_no_sex['Gastric_Cancer_Deaths'].fillna(0)
df_combined_rates_no_sex['Gastric_Cancer_Age_Specific_Rate'] = df_combined_rates_no_sex['Gastric_Cancer_Age_Specific_Rate'].fillna(0)
df_combined_rates_no_sex['Expected_Deaths_Gastric_Cancer_Standard_Pop'] = df_combined_rates_no_sex['Expected_Deaths_Gastric_Cancer_Standard_Pop'].fillna(0)
df_combined_rates_no_sex['Gastric_Cancer_Age_Adjusted_Rate'] = df_combined_rates_no_sex['Gastric_Cancer_Age_Adjusted_Rate'].fillna(0)


# Select and reorder columns to match the requested order
df_combined_final_no_sex = df_combined_rates_no_sex[[
    'Año',
    'Comuna',
    'Edad_Grupo_Cancer',
    'Poblacion',
    'Cancer_Deaths',
    'Gastric_Cancer_Deaths',
    'Cancer_Age_Specific_Rate',
    'Gastric_Cancer_Age_Specific_Rate',
    'Standard_Population',
    'Expected_Deaths_Cancer_Standard_Pop',
    'Expected_Deaths_Gastric_Cancer_Standard_Pop',
    'Cancer_Crude_Rate',
    'Gastric_Cancer_Crude_Rate',
    'Cancer_Age_Adjusted_Rate',
    'Gastric_Cancer_Age_Adjusted_Rate'
]]

# Display the head of the new combined dataframe
display(df_combined_final_no_sex.head())

# Display data for Comuna 1405, Año 2002
display(df_combined_final_no_sex[(df_combined_final_no_sex['Comuna'] == 1405) & (df_combined_final_no_sex['Año'] == 2002)])

,Año,Comuna,Edad_Grupo_Cancer,Poblacion,Cancer_Deaths,Gastric_Cancer_Deaths,Cancer_Age_Specific_Rate,Gastric_Cancer_Age_Specific_Rate,Standard_Population,Expected_Deaths_Cancer_Standard_Pop,Expected_Deaths_Gastric_Cancer_Standard_Pop,Cancer_Crude_Rate,Gastric_Cancer_Crude_Rate,Cancer_Age_Adjusted_Rate,Gastric_Cancer_Age_Adjusted_Rate
0,2002,1101,0-19,58777,5,0.0,8.506729,0.000000,4768447,405.638855,0.000000,156.672100,21.888014,240.225400,33.533696
1,2002,1101,20-59,98749,72,11.0,72.912131,11.139353,9955385,7258.683328,1108.965509,156.672100,21.888014,240.225400,33.533696
2,2002,1101,60+,16085,195,27.0,1212.309605,167.858253,2850171,34552.896798,4784.247249,156.672100,21.888014,240.225400,33.533696
3,2002,1401,60+,889,6,0.0,674.915636,0.000000,2850171,19236.249719,0.000000,61.019018,0.000000,109.458555,0.000000
4,2002,1405,20-59,1891,2,0.0,105.764146,0.000000,9955385,10529.227922,0.000000,193.370166,0.000000,214.371840,0.000000

,Año,Comuna,Edad_Grupo_Cancer,Poblacion,Cancer_Deaths,Gastric_Cancer_Deaths,Cancer_Age_Specific_Rate,Gastric_Cancer_Age_Specific_Rate,Standard_Population,Expected_Deaths_Cancer_Standard_Pop,Expected_Deaths_Gastric_Cancer_Standard_Pop,Cancer_Crude_Rate,Gastric_Cancer_Crude_Rate,Cancer_Age_Adjusted_Rate,Gastric_Cancer_Age_Adjusted_Rate
4,2002,1405,20-59,1891,2,0.0,105.764146,0.0,9955385,10529.227922,0.0,193.370166,0.0,214.37184,0.0
5,2002,1405,60+,525,5,0.0,952.380952,0.0,2850171,27144.485714,0.0,193.370166,0.0,214.37184,0.0

#Guardar dataframes combinados

In [ ]:
# Save the combined dataframe to parquet and excel files
output_dir = path_tasas

df_combined_final.to_parquet(f'{output_dir}Combined_Mortality_Rates.parquet', index=False)
df_combined_final_no_sex.to_parquet(f'{output_dir}Combined_Mortality_Rates_No_Sex.parquet', index=False)

print(f"Saved combined mortality rates dataframe to {output_dir}")
print(f"Saved combined mortality rates dataframe without sex disaggregation to {output_dir}")

Saved combined mortality rates dataframe to /content/drive/MyDrive/DSP 2025-1/cursos/PHDMISP2 Métodos de investigación en salud pública/seminario/Trabajo seminario/4 Tasas y razones de mortalidad/
Saved combined mortality rates dataframe without sex disaggregation to /content/drive/MyDrive/DSP 2025-1/cursos/PHDMISP2 Métodos de investigación en salud pública/seminario/Trabajo seminario/4 Tasas y razones de mortalidad/

#Guardar dataframes en excel

In [ ]:
# Save the combined dataframe to parquet and excel files
output_dir = path_tasas

df_combined_final_no_sex.to_excel(f'{output_dir}Combined_Mortality_Rates_No_Sex.xlsx', index=False)
df_combined_final.to_excel(f'{output_dir}Combined_Mortality_Rates.xlsx', index=False)

print(f"Saved combined mortality rates dataframe to {output_dir}")
print(f"Saved combined mortality rates dataframe without sex disaggregation to {output_dir}")